name: time_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.1.2
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  dio: ^5.3.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.0
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  fl_chart: ^1.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl_phone_field: ^3.2.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  auto_route_generator: ^10.2.4
  bloc_test: ^10.0.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  generate: true
